package main

import (
	"fmt"
)

var icons = map[string]string{
	"ai":           "\ue7b4",
	"android":      "\ue70e",
	"apple":        "\uf179",
	"as":           "\ue60b",
	"asm":          "󰘚",
	"audio":        "\uf1c7",
	"avro":         "\ue60b",
	"bf":           "\uf067",
	"binary":       "\uf471",
	"bzl":          "\ue63a",
	"c":            "\ue61e",
	"cfg":          "\uf423",
	"clj":          "\ue768",
	"coffee":       "\ue751",
	"conf":         "\ue615",
	"cpp":          "\ue61d",
	"cfm":          "\ue645",
	"cr":           "\ue62f",
	"cs":           "\ue648",
	"cson":         "\ue601",
	"css":          "\ue749",
	"cu":           "\ue64b",
	"d":            "\ue7af",
	"dart":         "\ue64c",
	"db":           "\uf1c0",
	"deb":          "\uf306",
	"diff":         "\uf440",
	"doc":          "\uf1c2",
	"dockerfile":   "\ue650",
	"dpkg":         "\uf17c",
	"ebook":        "\uf02d",
	"elm":          "\ue62c",
	"env":          "\uf462",
	"erl":          "\ue7b1",
	"ex":           "\ue62d",
	"f":            "󱈚",
	"file":         "\uf15b",
	"font":         "\uf031",
	"fs":           "\ue7a7",
	"gb":           "\ue272",
	"gform":        "\uf298",
	"git":          "\ue702",
	"go":           "\ue724",
	"graphql":      "\ue662",
	"glp":          "󰆧",
	"groovy":       "\ue775",
	"gruntfile.js": "\ue74c",
	"gulpfile.js":  "\ue610",
	"gv":           "\ue225",
	"h":            "\uf0fd",
	"haml":         "\ue664",
	"hs":           "\ue777",
	"html":         "\uf13b",
	"hx":           "\ue666",
	"ics":          "\uf073",
	"image":        "\uf1c5",
	"iml":          "\ue7b5",
	"ini":          "󰅪",
	"ino":          "\ue255",
	"iso":          "󰋊",
	"jade":         "\ue66c",
	"java":         "\ue738",
	"jenkinsfile":  "\ue767",
	"jl":           "\ue624",
	"js":           "\ue781",
	"json":         "\ue60b",
	"jsx":          "\ue7ba",
	"key":          "\uf43d",
	"ko":           "\uebc6",
	"kt":           "\ue634",
	"less":         "\ue758",
	"lock":         "\uf023",
	"log":          "\uf18d",
	"lua":          "\ue620",
	"maintainers":  "\uf0c0",
	"makefile":     "\ue20f",
	"md":           "\uf48a",
	"mjs":          "\ue718",
	"ml":           "󰘧",
	"mustache":     "\ue60f",
	"nc":           "󰋁",
	"nim":          "\ue677",
	"nix":          "\uf313",
	"npmignore":    "\ue71e",
	"package":      "󰏗",
	"passwd":       "\uf023",
	"patch":        "\uf440",
	"pdf":          "\uf1c1",
	"php":          "\ue608",
	"pl":           "\ue7a1",
	"prisma":       "\ue684",
	"ppt":          "\uf1c4",
	"psd":          "\ue7b8",
	"py":           "\ue606",
	"r":            "\ue68a",
	"rb":           "\ue21e",
	"rdb":          "\ue76d",
	"rpm":          "\uf17c",
	"rs":           "\ue7a8",
	"rss":          "\uf09e",
	"rst":          "󰅫",
	"rubydoc":      "\ue73b",
	"sass":         "\ue603",
	"scala":        "\ue737",
	"shell":        "\uf489",
	"shp":          "󰙞",
	"sol":          "",
	"sqlite":       "\ue7c4",
	"styl":         "\ue600",
	"svelte":       "\ue697",
	"swift":        "\ue755",
	"tex":          "\u222b",
	"tf":           "\ue69a",
	"toml":         "\ue6b2",
	"ts":           "\ue628",
	"twig":         "\ue61c",
	"txt":          "\uf15c",
	"vagrantfile":  "\ue21e",
	"video":        "\uf03d",
	"vim":          "\ue62b",
	"vue":          "\ue6a0",
	"windows":      "\uf17a",
	"xls":          "\uf1c3",
	"xml":          "\ue796",
	"yml":          "\ue601",
	"yaml":         "\ue601",
	"zig":          "\ue6a9",
	"zip":          "\uf410",
}

func getFileIcon(ext string) string {
	if icon, ok := icons[ext]; ok {
		return icon
	}

	return icons["file"]
}

var folders = map[string]string{
	".atom":                 "\ue764",
	".aws":                  "\ue7ad",
	".docker":               "\ue7b0",
	".gem":                  "\ue21e",
	".git":                  "\ue5fb",
	".git-credential-cache": "\ue5fb",
	".github":               "\ue5fd",
	".npm":                  "\ue5fa",
	".nvm":                  "\ue718",
	".rvm":                  "\ue21e",
	".Trash":                "\uf1f8",
	".vscode":               "\ue70c",
	".vim":                  "\ue62b",
	"config":                "\ue5fc",
	"folder":                "\uf07c",
	"hidden":                "\uf023",
	"node_modules":          "\ue5fa",
}

func getFolderIcon(ext string) string {
	if icon, ok := folders[ext]; ok {
		return icon
	}

	return folders["folder"]
}

func printIcon(name string) {
	if icon {
		fmt.Print(name)
	}
}
